### ISSUE TITLE
eks IRSA for authentication

### ISSUE THREAD

**Issue by haarchri** [chanwit/tf-controller#17]
is EKS IRSA possible for authentication to aws-api instead of using static credentials?

**Comment by chanwit** [comment]
Everything that worked via normal `terraform` command would work with this controller because it just uses HashiCorp's TFExec to directly execute the Terraform binary and other provider binaries inside the container. Please let me know if you got any error.

**Comment by chanwit** [comment]
But it's going to be a handy feature indeed!

**Comment by chanwit** [comment]
ref: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

**Comment by phoban01** [comment]
@haarchri This is currently possible by annotating the service account used by the Terraform controller.

If you installed the controller following the quickstart guide from the README then the following should work (substituting the appropriate `ROLE_ARN`):

`kubectl -n flux-system serviceaccount default eks.amazon.com/role-arn=ROLE_ARN`

Just ensure the trust policy on the role lines up with the namespace/service account and it should work.
