### ISSUE TITLE
Write a full test scenario for the disableDriftDetection feature

### ISSUE THREAD

**Issue by chanwit** [chanwit/tf-controller#24]
The new `.spec.disableDriftDetection` requires a full specification as the following.

- a Terraform object with "auto" mode performs "plan" and "apply", with interval like 10s. We set 'disableDriftDetection" to "true"
- then we wait 20s.
- the Ready condition should *NOT* be changed to "NoDrift", as the detection is disabled.

**Comment by phoban01** [comment]
@chanwit I can follow up with this.

**Comment by chanwit** [comment]
Thank you @phoban01
