### ISSUE TITLE
Add helm chart for TF-controller

### ISSUE THREAD

**Issue by chanwit** [chanwit/tf-controller#36]

**Comment by tomhuang12** [comment]
i'll take this

**Comment by tomhuang12** [comment]
Do we want to create a separate git repo to use as a helm repo?

**Comment by chanwit** [comment]
Somewhere here, https://github.com/tf-controller?
If you think it's a good idea, I can add you there.

**Comment by tomhuang12** [comment]
Yes that would be great. Thanks!

**Comment by chanwit** [comment]
Sent.
Please feel free to create a repo there. Let me know if you got an access problem.

**Comment by tomhuang12** [comment]
Please see https://github.com/tf-controller/charts. Let me know if you have any feedback 😄

**Comment by tomhuang12** [comment]
Also, I am using my personal PAT to run the release action in the repository currently. If you have a token, please update it in that repository.

**Comment by chanwit** [comment]
Thank you, I'll take care of it.

**Comment by chanwit** [comment]
I'm going to test installing the Helm chart with Flux's HemlRelease, and post the result here.

**Comment by chanwit** [comment]
The chart worked perfectly
